<a href="https://colab.research.google.com/github/anubhavgupta1/DeepLearning/blob/master/1_numpy_array.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy as np


In [12]:
x = np.array(range(5))
type(x)

numpy.ndarray

In [13]:
x

array([0, 1, 2, 3, 4])

In [14]:
y = np.asarray(x, float)
print(y)

[0. 1. 2. 3. 4.]


In [16]:
z = [4,5,10,12]
z = np.asarray(z)
z

array([ 4,  5, 10, 12])

In [18]:
mat = np.array([[1,2,3],[4,5,6]])
mat

array([[1, 2, 3],
       [4, 5, 6]])

In [19]:
mat.shape

(2, 3)

In [23]:
mat[0,0:3]


array([1, 2, 3])

In [24]:
mat[0,:]

array([1, 2, 3])

In [26]:
mat = np.zeros((4,5))
mat

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [29]:
mat = np.eye(4,4)
mat

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [31]:
mat = np.random.random((4,5))
mat

array([[0.80058815, 0.29779612, 0.95074478, 0.67125678, 0.13447179],
       [0.64792767, 0.61162415, 0.26859853, 0.56802434, 0.90586338],
       [0.99456954, 0.03790229, 0.39058368, 0.18927614, 0.84951587],
       [0.28580758, 0.71684914, 0.73891095, 0.12778717, 0.17450691]])

In [32]:
Z = mat.T
Z

array([[0.80058815, 0.64792767, 0.99456954, 0.28580758],
       [0.29779612, 0.61162415, 0.03790229, 0.71684914],
       [0.95074478, 0.26859853, 0.39058368, 0.73891095],
       [0.67125678, 0.56802434, 0.18927614, 0.12778717],
       [0.13447179, 0.90586338, 0.84951587, 0.17450691]])

In [34]:
Z = Z.reshape(20,1)
Z

array([[0.80058815],
       [0.64792767],
       [0.99456954],
       [0.28580758],
       [0.29779612],
       [0.61162415],
       [0.03790229],
       [0.71684914],
       [0.95074478],
       [0.26859853],
       [0.39058368],
       [0.73891095],
       [0.67125678],
       [0.56802434],
       [0.18927614],
       [0.12778717],
       [0.13447179],
       [0.90586338],
       [0.84951587],
       [0.17450691]])

In [37]:
A = np.arange(5)
A

array([0, 1, 2, 3, 4])

In [38]:
B = np.arange(5)
A + B

array([0, 2, 4, 6, 8])

In [39]:
A-B

array([0, 0, 0, 0, 0])

In [40]:
A*B

array([ 0,  1,  4,  9, 16])

In [48]:
A = np.random.random((2,3))
A

array([[0.6889747 , 0.41260884, 0.42201498],
       [0.79929559, 0.16629237, 0.1225732 ]])

In [49]:
A = A * 10
A

array([[6.88974704, 4.12608836, 4.22014984],
       [7.99295586, 1.66292369, 1.22573199]])

In [50]:
A = np.floor(A)
A

array([[6., 4., 4.],
       [7., 1., 1.]])

In [51]:
x1 = [1,2,3]
x2 = [-1,0,1]
p = np.inner(x1,x2)
p

2

In [52]:
p = np.outer(x1,x2)
p

array([[-1,  0,  1],
       [-2,  0,  2],
       [-3,  0,  3]])

In [53]:
A = np.ones((2,3))
A

array([[1., 1., 1.],
       [1., 1., 1.]])

In [54]:
B = np.ones((3,2))
B

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [55]:
np.dot(A,B)

array([[3., 3.],
       [3., 3.]])

In [57]:
A.sum()

6.0

In [58]:
A.sum(axis=0)

array([2., 2., 2.])

In [59]:
A.sum(axis =1)

array([3., 3.])

In [60]:
A.max()

1.0