<a href="https://colab.research.google.com/github/anubhavgupta1/DeepLearning/blob/master/1_python_basics_meshgrid.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.colors
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, mean_squared_error, log_loss
from tqdm import tqdm_notebook 
import seaborn as sns
import imageio
from IPython.display import HTML


from sklearn.preprocessing import OneHotEncoder
from sklearn.datasets import make_blobs

from IPython import display

In [2]:
my_cmap = matplotlib.colors.LinearSegmentedColormap.from_list("",["red","yellow","green"])
np.random.seed(0)
data, labels = make_blobs(n_samples=1000,n_features=2, centers=4,random_state=0)
print(data.shape,"\n", labels.shape)
labels_orig = labels
labels = np.mod(labels_orig,2)
X_train, X_val, Y_train, Y_val = train_test_split(data,labels,stratify=labels,random_state =0)
print("Train data : \n", X_train.shape, Y_train.shape)
print("Validation data : \n", X_val.shape, Y_val.shape)

(1000, 2) 
 (1000,)
Train data : 
 (750, 2) (750,)
Validation data : 
 (250, 2) (250,)


In [10]:
print(X_train[:,0].min(),X_train[:,0].max())
print(X_train[:,0].min()-0.5,X_train[:,0].max()+0.5)

-4.521516873449524 4.40191455195944
-5.021516873449524 4.90191455195944


In [11]:
print(X_train[:,1].min(),X_train[:,1].max())
print(X_train[:,1].min()-0.5,X_train[:,1].max()+0.5)

-1.9368908453367655 10.375691636400767
-2.4368908453367655 10.875691636400767


In [13]:
np.arange(2,3,0.1)

array([2. , 2.1, 2.2, 2.3, 2.4, 2.5, 2.6, 2.7, 2.8, 2.9])

In [18]:
print(len(np.arange(X_train[:,0].min()-0.5,X_train[:,0].max()+0.5,0.2)))
print(len(np.arange(X_train[:,1].min()-0.5,X_train[:,1].max()+0.5,0.2)))

50
67


In [0]:
x = np.arange(X_train[:,0].min()-0.5,X_train[:,0].max()+0.5,0.2)
y = np.arange(X_train[:,1].min()-0.5,X_train[:,1].max()+0.5,0.2)

In [21]:
xx , yy = np.meshgrid(x,y)
print(xx.shape, yy.shape)

(67, 50) (67, 50)


In [22]:
a, b = np.meshgrid(np.asarray([2,3]), np.asarray([4,5,6]))
print(a.shape, b.shape)

(3, 2) (3, 2)


In [23]:
a

array([[2, 3],
       [2, 3],
       [2, 3]])

In [24]:
b

array([[4, 4],
       [5, 5],
       [6, 6]])